set_property IOSTANDARD LVCMOS25 [get_ports {i_emdint i_e*}]
set_property IOSTANDARD LVCMOS25 [get_ports io_emdio]
set_property IOSTANDARD LVCMOS25 [get_ports {o_etxd[*]}]
set_property IOSTANDARD LVCMOS25 [get_ports o_erefclk]
set_property IOSTANDARD LVCMOS25 [get_ports o_emdc]
set_property IOSTANDARD LVCMOS25 [get_ports o_erstn]
set_property IOSTANDARD LVCMOS25 [get_ports o_etx_en]
set_property IOSTANDARD LVCMOS25 [get_ports o_etx_er]
set_property IOSTANDARD LVCMOS15 [get_ports {o_led[*]}]
set_property IOSTANDARD LVCMOS15 [get_ports {i_dip[*]}]
set_property IOSTANDARD LVTTL [get_ports {sd_*}]
# on board differential clock, 100MHz
set_property PACKAGE_PIN E3 [get_ports clk_p]

# UART Pins
set_property PACKAGE_PIN A9 [get_ports rxd]
set_property IOSTANDARD LVCMOS25 [get_ports rxd]
set_property PACKAGE_PIN D10 [get_ports txd]
set_property IOSTANDARD LVCMOS25 [get_ports txd]

# SD/SPI Pins
#set_property PACKAGE_PIN AC21 [get_ports spi_cs]
#set_property IOSTANDARD LVCMOS25 [get_ports spi_cs]
#set_property PACKAGE_PIN AB23 [get_ports spi_sclk]
#set_property IOSTANDARD LVCMOS25 [get_ports spi_sclk]
#set_property PACKAGE_PIN AB22 [get_ports spi_mosi]
#set_property IOSTANDARD LVCMOS25 [get_ports spi_mosi]
#set_property PACKAGE_PIN AC20 [get_ports spi_miso]
#set_property IOSTANDARD LVCMOS25 [get_ports spi_miso]
# Is this right ? (needs correcting)
set_property PACKAGE_PIN G13 [get_ports sd_reset]
set_property PACKAGE_PIN B11 [get_ports sd_detect]
set_property PACKAGE_PIN A11 [get_ports sd_cmd]
set_property PACKAGE_PIN D12 [get_ports sd_sclk]
set_property PACKAGE_PIN D13 [get_ports {sd_dat[2]}]
set_property PACKAGE_PIN B18 [get_ports {sd_dat[1]}]
set_property PACKAGE_PIN A18 [get_ports {sd_dat[0]}]
set_property PACKAGE_PIN K16 [get_ports {sd_dat[3]}]
# Ethernet
set_property PACKAGE_PIN K13 [get_ports io_emdio]
set_property PACKAGE_PIN G18 [get_ports o_erefclk]
set_property PACKAGE_PIN C16 [get_ports o_erstn]
set_property PACKAGE_PIN H15 [get_ports o_etx_en]
set_property PACKAGE_PIN H16 [get_ports i_etx_clk]
set_property PACKAGE_PIN H14 [get_ports {o_etxd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {o_etxd[0]}]
set_property PACKAGE_PIN J14 [get_ports {o_etxd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {o_etxd[1]}]
set_property PACKAGE_PIN J13 [get_ports {o_etxd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {o_etxd[2]}]
set_property PACKAGE_PIN H17 [get_ports {o_etxd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {o_etxd[3]}]
set_property PACKAGE_PIN F16 [get_ports o_emdc]
set_property PACKAGE_PIN G16 [get_ports i_erx_dv]
set_property PACKAGE_PIN F15 [get_ports i_erx_clk]
set_property PACKAGE_PIN C17 [get_ports i_erx_er]
set_property PACKAGE_PIN D18 [get_ports {i_erxd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {i_erxd[0]}]
set_property PACKAGE_PIN E17 [get_ports {i_erxd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {i_erxd[1]}]
set_property PACKAGE_PIN E18 [get_ports {i_erxd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {i_erxd[2]}]
set_property PACKAGE_PIN G17 [get_ports {i_erxd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {i_erxd[3]}]

set_property PACKAGE_PIN A8 [get_ports {i_dip[0]}]
set_property PACKAGE_PIN C11 [get_ports {i_dip[1]}]
set_property PACKAGE_PIN C10 [get_ports {i_dip[2]}]
set_property PACKAGE_PIN A10 [get_ports {i_dip[3]}]

set_property PACKAGE_PIN H5 [get_ports {o_led[0]}]
set_property PACKAGE_PIN J5 [get_ports {o_led[1]}]
set_property PACKAGE_PIN T9 [get_ports {o_led[2]}]
set_property PACKAGE_PIN T10 [get_ports {o_led[3]}]
# These are dummies that just go to unused LEDs
set_property PACKAGE_PIN E1 [get_ports PS2_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
set_property PACKAGE_PIN F6 [get_ports PS2_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]

# BUTTON
set_property PACKAGE_PIN D9 [get_ports {GPIO_SW_N}]
set_property PACKAGE_PIN C9 [get_ports {GPIO_SW_S}]
set_property PACKAGE_PIN B9  [get_ports {GPIO_SW_W}]
set_property PACKAGE_PIN B8  [get_ports {GPIO_SW_E}]
#set_property PACKAGE_PIN G12  [get_ports {GPIO_SW_C}]

set_property IOSTANDARD LVCMOS15 [get_ports {GPIO_SW_N}]
set_property IOSTANDARD LVCMOS15 [get_ports {GPIO_SW_S}]
set_property IOSTANDARD LVCMOS15 [get_ports {GPIO_SW_W}]
set_property IOSTANDARD LVCMOS15 [get_ports {GPIO_SW_E}]
set_property IOSTANDARD LVCMOS15 [get_ports {GPIO_SW_C}]
